#!/bin/sh
#
#++
# = SECRETS(1)
# :man manual: msys operations manual
# :Revision: 1.0
# :Author: A Liu Ly
#
# == NAME
#
# secrets - upload secrets
#
# == SYNOPSIS
#
# *msecrets* _[--secrets=file] [--admkeys=keys]_ [-t|--test]_ _system_
#
# == DESCRIPTION
#
# This script uploads secret files to target systems.  It is
# done outside the normal *msys* config process in order to avoid
# logging the payload.  By default *msys* will log configuration scripts.
#
# == OPTIONS
#
# *--secrets=* file::
#    Secrets configuration file.  Defaults to `/etc/secrets.cfg`.
# *--admkeys=* keys::
#    Admin ssh keys.  Defaults to `/etc/msys.keys`.
# *-t|--test*
#    Test mode.
#
# == ENVIRONMENT
#
# *SECRETS_CFG*:: Path to secrets config file.
# *ADM_KEYS*:: Path to admin keys file.
#
# == SEE ALSO
#
# msys(8)
#
#--
set -euf -o pipefail

script_dir=$(cd $(dirname $0) && pwd)

[ -z "$SECRETS_CFG" ] && SECRETS_CFG=/etc/secrets.cfg
[ -z "$ADM_KEYS" ] && ADM_KEYS=/etc/msys.keys

test=false

while [ $# -gt 0 ] ; do
  case "$1" in
    -t|--test)
      test=true
      shift
      ;;
    --secrets=*)
      SECRET_CFG=${1#--secrets=}
      shift
      ;;
    --admkeys=*)
      ADM_KEYS=${1#--admkeys=}
      shift
      ;;
    *)
      break
      ;;
  esac
done

eval "$script_dir"/ashlib/ashlib

(
  echo '#!/bin/sh'
  for s in core.sh fixfile.sh
  do
    cat "$ASHLIB/$s"
  done
  if [ -f "$SECRETS_CFG" ] ; then
    echo 'secrets=/etc/secrets.cfg'
    echo 'fixfile --mode=600 "$secrets" <<EOF'
    cat "$SECRETS_CFG"
    echo ''
    echo 'EOF'
    echo 'MD5a:$(uname -n):$(md5sum "$secrets")'
  fi
  if [ -f "$ADM_KEYS" ] ; then
    echo 'syskeys=/etc/msys.keys'
    (
      set -nv
      if [ -d /etc/dropbear ] ; then
	authkeys=/etc/dropbear/authorized_keys
      else
	authkeys=$HOME/.ssh/authorized_keys
	mkdir -p $(dirname $authkeys)
      fi

      if [ -f $syskeys ] ; then
	old=$(md5sum $syskeys | awk '{print $1}')
      else
	old="___"
      fi
    )
    echo 'fixfile --mode=600 "$syskeys" <<EOF'
    cat "$ADM_KEYS"
    echo ''
    echo 'EOF'
    echo 'MD5b:$(uname -n):$(md5sum "$syskeys")'
    (
      set -nv
      new=$(md5sum $syskeys | awk '{print $1}')
      [ "$new" = "$old" ] && exit

      if [ -f $authkeys ] ; then
	cur=$(md5sum $authkeys | awk '{print $1}')
	#echo "cur=$cur old=$old"
	if [ x"$cur" != x"$old" ] ;then
	  warn "$authkeys does not use $syskeys"
	  exit
	fi
	warn "Updating $authkeys..."
      else
	warn "Initializing $authkeys..."
      fi
      cp -a $syskeys $authkeys
    )
  fi
) > x 

exit






  
  
"$ASHLIB"/ashcc 


exit

exit
if $test  ; then
  
  exec $script_dir/msys \
    "-DMSYS_SECRETS_CFG='$SECRETS_CFG'" \
    "-DMSYS_ADMIN_KEYS='$ADM_KEYS'" \
    -t secrets
else
  rv=0
  for ip in "$@"
  do
    $script_dir/msys \
      --no-archive \
      "-DMSYS_SECRETS_CFG='$SECRETS_CFG'" \
      "-DMSYS_ADMIN_KEYS='$ADM_KEYS'" \
      --ssh="$ip" secrets
    rv=$(expr $rv + $?)
  done
  exit $rv
fi


#!/bin/sh
#

